export default class Technical {
  constructor({
    pkTecnico = null,
    dataCad = null,
    dataAtu = null,
    nmTecnico,
    fone1 = "(  )    -     R:",
    fone2 = "(  )    -     R:",
    fkCodUsu = null,
    ativo = 1,
    fkEmpresa = null,
    estadoCivil = null,
    conjuge = null,
    nomeMae = null,
    nomePai = null,
    dataAdmissao = null,
    salario = null,
    fkFuncao = null,
    horasTrabalho = null,
    cpf = null,
    rg = null,
    endereco = null,
    num = null,
    cep = null,
    fkCidade = null,
    bairro = null,
    cbo = null,
    carteiraTrabalho = null,
    complemento = null,
    crea = null,
    dataNasc = null,
    corAgenda = null,
    pis = null,
    valorHora = 0,
    email = null,
    obs = null,
    celular = "(  )    -     R:",
    fone1Whatsapp = 0,
    fone2Whatsapp = 0,
    celularWhatsapp = 0,
    deOndeVemAlteracao = 0,
    comercial = null,
    financeiro = null,
    nroMatricula = null,
    consumidorFinal = 1,
    fkSacaDoCedente = null,
    pkAntigo = null,
    cadastroCas = null,
  }) {
    this.pkTecnico = pkTecnico;
    this.dataCad = dataCad;
    this.dataAtu = dataAtu;
    this.nmTecnico = nmTecnico;
    this.fone1 = fone1;
    this.fone2 = fone2;
    this.fkCodUsu = fkCodUsu;
    this.ativo = ativo;
    this.fkEmpresa = fkEmpresa;
    this.estadoCivil = estadoCivil;
    this.conjuge = conjuge;
    this.nomeMae = nomeMae;
    this.nomePai = nomePai;
    this.dataAdmissao = dataAdmissao;
    this.salario = salario;
    this.fkFuncao = fkFuncao;
    this.horasTrabalho = horasTrabalho;
    this.cpf = cpf;
    this.rg = rg;
    this.endereco = endereco;
    this.num = num;
    this.cep = cep;
    this.fkCidade = fkCidade;
    this.bairro = bairro;
    this.cbo = cbo;
    this.carteiraTrabalho = carteiraTrabalho;
    this.complemento = complemento;
    this.crea = crea;
    this.dataNasc = dataNasc;
    this.corAgenda = corAgenda;
    this.pis = pis;
    this.valorHora = valorHora;
    this.email = email;
    this.obs = obs;
    this.celular = celular;
    this.fone1Whatsapp = fone1Whatsapp;
    this.fone2Whatsapp = fone2Whatsapp;
    this.celularWhatsapp = celularWhatsapp;
    this.deOndeVemAlteracao = deOndeVemAlteracao;
    this.comercial = comercial;
    this.financeiro = financeiro;
    this.nroMatricula = nroMatricula;
    this.consumidorFinal = consumidorFinal;
    this.fkSacaDoCedente = fkSacaDoCedente;
    this.pkAntigo = pkAntigo;
  }
}
